server {
    listen 80;
    server_name unipass.click www.unipass.click;
    client_max_body_size 50M;

    # Phục vụ file tĩnh cho frontend
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy các request API tới backend
    location ~ ^/(api|management|v3/api-docs|swagger-ui|uploads) {
        # Đảm bảo backend container tên là 'unipassapi' và port 8080 trong docker-compose
        proxy_pass http://unipassapi:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Proxy WebSocket cho Chat (STOMP/SockJS)
    location /websocket/ {
        proxy_pass http://unipassapi:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
