# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: unipassWebApp
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: Y2I1OTBmYjZmM2MxOWE5ZDNkOGEyZDNkZGIyY2NmOTg0ODY2NzA5Y2Q3MzM1ZTA0MWI3MmY4MjJiNWRhZDNiYTUxYTA5MjNiNzg2YTIxYzFmMGM5NzdjMWYxZTU2OTJmMWM5NWQ4YTdiMDk4NjQ5NzMzODZmN2QwZmM0ZDc1MjI=
